apiVersion: v1
kind: Service
metadata:
  name: {{ include "plan-a.fullname" . }}
  labels:
    {{- include "plan-a.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "plan-a.selectorLabels" . | nindent 4 }}
